project:
  type: website
  output-dir: docs

website:
  title: "David Mawdsley"
  navbar:
    background: primary
    left:
      - about.qmd
      - blog.qmd
  open-graph: true 
  page-footer:
    center:
    - text: <a href="https://www.github.com/mawds">Github</a> <a rel="me" href="https://mastodon.me.uk/@mawds">Mastodon</a>
    
  
    
format:
  html:
    theme: superhero 
    css: styles.css
    toc: true
    anchor-sections: true
    smooth-scroll: true



