project:
  type: website
  output-dir: docs

website:
  title: "David Mawdsley"
  navbar:
    background: primary
    left:
      - about.qmd
      - blog.qmd
  open-graph: true 
    
format:
  html:
    theme: superhero 
    css: styles.css
    toc: true
    anchor-sections: true
    smooth-scroll: true



